from fastapi import APIRouter

from whatsapp_gateway.configuration.audience_crud import router as audience_crud_router
from whatsapp_gateway.configuration.audience_members import router as audience_members_router
from whatsapp_gateway.configuration.options import router as options_router
from whatsapp_gateway.configuration.profile_crud import router as profile_crud_router
from whatsapp_gateway.configuration.recipient_scopes import router as recipient_scopes_router
from whatsapp_gateway.configuration.report_types import router as report_types_router
from whatsapp_gateway.configuration.reporting_routes import router as reporting_routes_router

router = APIRouter()
router.include_router(options_router)
router.include_router(report_types_router)
router.include_router(recipient_scopes_router)
router.include_router(audience_crud_router)
router.include_router(audience_members_router)
router.include_router(profile_crud_router)
router.include_router(reporting_routes_router)
