"""whatsapp dispatch configuration

Revision ID: 2a3df264ca01
Revises: 2a46410c6e53
Create Date: 2026-07-13 16:47:16.593515
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '2a3df264ca01'
down_revision: Union[str, Sequence[str], None] = '2a46410c6e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_applications_enabled'), 'whatsapp_applications', ['enabled'], unique=False)
    op.create_index(op.f('ix_whatsapp_applications_key'), 'whatsapp_applications', ['key'], unique=True)
    op.create_index(op.f('ix_whatsapp_applications_name'), 'whatsapp_applications', ['name'], unique=False)
    op.create_table('whatsapp_audiences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['whatsapp_applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'key', name='uq_whatsapp_audiences_application_key'),
    sa.UniqueConstraint('id', 'application_id', name='uq_whatsapp_audiences_id_application')
    )
    op.create_index(op.f('ix_whatsapp_audiences_application_id'), 'whatsapp_audiences', ['application_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_audiences_enabled'), 'whatsapp_audiences', ['enabled'], unique=False)
    op.create_index(op.f('ix_whatsapp_audiences_key'), 'whatsapp_audiences', ['key'], unique=False)
    op.create_index(op.f('ix_whatsapp_audiences_name'), 'whatsapp_audiences', ['name'], unique=False)
    op.create_table('whatsapp_report_types',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('artifact_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['whatsapp_applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'key', name='uq_whatsapp_report_types_application_key'),
    sa.UniqueConstraint('id', 'application_id', name='uq_whatsapp_report_types_id_application')
    )
    op.create_index(op.f('ix_whatsapp_report_types_application_id'), 'whatsapp_report_types', ['application_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_report_types_artifact_kind'), 'whatsapp_report_types', ['artifact_kind'], unique=False)
    op.create_index(op.f('ix_whatsapp_report_types_enabled'), 'whatsapp_report_types', ['enabled'], unique=False)
    op.create_index(op.f('ix_whatsapp_report_types_key'), 'whatsapp_report_types', ['key'], unique=False)
    op.create_index(op.f('ix_whatsapp_report_types_name'), 'whatsapp_report_types', ['name'], unique=False)
    op.create_table('whatsapp_audience_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('audience_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('directory_group_id', sa.Uuid(), nullable=True),
    sa.Column('directory_contact_id', sa.Uuid(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(target_type = 'group' AND directory_group_id IS NOT NULL AND directory_contact_id IS NULL) OR (target_type = 'contact' AND directory_contact_id IS NOT NULL AND directory_group_id IS NULL)", name='ck_whatsapp_audience_members_target'),
    sa.CheckConstraint("target_type IN ('group', 'contact')", name='ck_whatsapp_audience_members_type'),
    sa.ForeignKeyConstraint(['audience_id'], ['whatsapp_audiences.id'], ),
    sa.ForeignKeyConstraint(['directory_contact_id'], ['whatsapp_directory_contacts.id'], ),
    sa.ForeignKeyConstraint(['directory_group_id'], ['whatsapp_directory_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audience_id', 'target_key', name='uq_whatsapp_audience_members_target')
    )
    op.create_index(op.f('ix_whatsapp_audience_members_audience_id'), 'whatsapp_audience_members', ['audience_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_audience_members_directory_contact_id'), 'whatsapp_audience_members', ['directory_contact_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_audience_members_directory_group_id'), 'whatsapp_audience_members', ['directory_group_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_audience_members_enabled'), 'whatsapp_audience_members', ['enabled'], unique=False)
    op.create_index(op.f('ix_whatsapp_audience_members_target_key'), 'whatsapp_audience_members', ['target_key'], unique=False)
    op.create_index(op.f('ix_whatsapp_audience_members_target_type'), 'whatsapp_audience_members', ['target_type'], unique=False)
    op.create_table('whatsapp_dispatch_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_type_id', sa.Uuid(), nullable=False),
    sa.Column('audience_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('wing_id', sa.Uuid(), nullable=True),
    sa.Column('delivery_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('require_approval', sa.Boolean(), nullable=False),
    sa.Column('fallback_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('messages_per_minute', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("delivery_mode IN ('groups', 'individuals', 'mixed')", name='ck_whatsapp_profiles_delivery_mode'),
    sa.CheckConstraint("fallback_policy IN ('none', 'same_scope')", name='ck_whatsapp_profiles_fallback_policy'),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], ),
    sa.ForeignKeyConstraint(['audience_id', 'application_id'], ['whatsapp_audiences.id', 'whatsapp_audiences.application_id'], name='fk_whatsapp_profiles_audience_application'),
    sa.ForeignKeyConstraint(['report_type_id', 'application_id'], ['whatsapp_report_types.id', 'whatsapp_report_types.application_id'], name='fk_whatsapp_profiles_report_application'),
    sa.ForeignKeyConstraint(['template_id'], ['whatsapp_templates.id'], ),
    sa.ForeignKeyConstraint(['wing_id'], ['wings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'key', name='uq_whatsapp_profiles_application_key')
    )
    op.create_index(op.f('ix_whatsapp_dispatch_profiles_account_id'), 'whatsapp_dispatch_profiles', ['account_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_dispatch_profiles_application_id'), 'whatsapp_dispatch_profiles', ['application_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_dispatch_profiles_audience_id'), 'whatsapp_dispatch_profiles', ['audience_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_dispatch_profiles_delivery_mode'), 'whatsapp_dispatch_profiles', ['delivery_mode'], unique=False)
    op.create_index(op.f('ix_whatsapp_dispatch_profiles_enabled'), 'whatsapp_dispatch_profiles', ['enabled'], unique=False)
    op.create_index(op.f('ix_whatsapp_dispatch_profiles_fallback_policy'), 'whatsapp_dispatch_profiles', ['fallback_policy'], unique=False)
    op.create_index(op.f('ix_whatsapp_dispatch_profiles_key'), 'whatsapp_dispatch_profiles', ['key'], unique=False)
    op.create_index(op.f('ix_whatsapp_dispatch_profiles_name'), 'whatsapp_dispatch_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_whatsapp_dispatch_profiles_report_type_id'), 'whatsapp_dispatch_profiles', ['report_type_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_dispatch_profiles_template_id'), 'whatsapp_dispatch_profiles', ['template_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_dispatch_profiles_wing_id'), 'whatsapp_dispatch_profiles', ['wing_id'], unique=False)
    op.add_column('whatsapp_templates', sa.Column('application_id', sa.Uuid(), nullable=True))
    op.add_column('whatsapp_templates', sa.Column('report_type_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_whatsapp_templates_application_id'), 'whatsapp_templates', ['application_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_report_type_id'), 'whatsapp_templates', ['report_type_id'], unique=False)
    op.create_foreign_key('fk_whatsapp_templates_application', 'whatsapp_templates', 'whatsapp_applications', ['application_id'], ['id'])
    op.create_foreign_key('fk_whatsapp_templates_report_type', 'whatsapp_templates', 'whatsapp_report_types', ['report_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_whatsapp_templates_report_type', 'whatsapp_templates', type_='foreignkey')
    op.drop_constraint('fk_whatsapp_templates_application', 'whatsapp_templates', type_='foreignkey')
    op.drop_index(op.f('ix_whatsapp_templates_report_type_id'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_application_id'), table_name='whatsapp_templates')
    op.drop_column('whatsapp_templates', 'report_type_id')
    op.drop_column('whatsapp_templates', 'application_id')
    op.drop_index(op.f('ix_whatsapp_dispatch_profiles_wing_id'), table_name='whatsapp_dispatch_profiles')
    op.drop_index(op.f('ix_whatsapp_dispatch_profiles_template_id'), table_name='whatsapp_dispatch_profiles')
    op.drop_index(op.f('ix_whatsapp_dispatch_profiles_report_type_id'), table_name='whatsapp_dispatch_profiles')
    op.drop_index(op.f('ix_whatsapp_dispatch_profiles_name'), table_name='whatsapp_dispatch_profiles')
    op.drop_index(op.f('ix_whatsapp_dispatch_profiles_key'), table_name='whatsapp_dispatch_profiles')
    op.drop_index(op.f('ix_whatsapp_dispatch_profiles_fallback_policy'), table_name='whatsapp_dispatch_profiles')
    op.drop_index(op.f('ix_whatsapp_dispatch_profiles_enabled'), table_name='whatsapp_dispatch_profiles')
    op.drop_index(op.f('ix_whatsapp_dispatch_profiles_delivery_mode'), table_name='whatsapp_dispatch_profiles')
    op.drop_index(op.f('ix_whatsapp_dispatch_profiles_audience_id'), table_name='whatsapp_dispatch_profiles')
    op.drop_index(op.f('ix_whatsapp_dispatch_profiles_application_id'), table_name='whatsapp_dispatch_profiles')
    op.drop_index(op.f('ix_whatsapp_dispatch_profiles_account_id'), table_name='whatsapp_dispatch_profiles')
    op.drop_table('whatsapp_dispatch_profiles')
    op.drop_index(op.f('ix_whatsapp_audience_members_target_type'), table_name='whatsapp_audience_members')
    op.drop_index(op.f('ix_whatsapp_audience_members_target_key'), table_name='whatsapp_audience_members')
    op.drop_index(op.f('ix_whatsapp_audience_members_enabled'), table_name='whatsapp_audience_members')
    op.drop_index(op.f('ix_whatsapp_audience_members_directory_group_id'), table_name='whatsapp_audience_members')
    op.drop_index(op.f('ix_whatsapp_audience_members_directory_contact_id'), table_name='whatsapp_audience_members')
    op.drop_index(op.f('ix_whatsapp_audience_members_audience_id'), table_name='whatsapp_audience_members')
    op.drop_table('whatsapp_audience_members')
    op.drop_index(op.f('ix_whatsapp_report_types_name'), table_name='whatsapp_report_types')
    op.drop_index(op.f('ix_whatsapp_report_types_key'), table_name='whatsapp_report_types')
    op.drop_index(op.f('ix_whatsapp_report_types_enabled'), table_name='whatsapp_report_types')
    op.drop_index(op.f('ix_whatsapp_report_types_artifact_kind'), table_name='whatsapp_report_types')
    op.drop_index(op.f('ix_whatsapp_report_types_application_id'), table_name='whatsapp_report_types')
    op.drop_table('whatsapp_report_types')
    op.drop_index(op.f('ix_whatsapp_audiences_name'), table_name='whatsapp_audiences')
    op.drop_index(op.f('ix_whatsapp_audiences_key'), table_name='whatsapp_audiences')
    op.drop_index(op.f('ix_whatsapp_audiences_enabled'), table_name='whatsapp_audiences')
    op.drop_index(op.f('ix_whatsapp_audiences_application_id'), table_name='whatsapp_audiences')
    op.drop_table('whatsapp_audiences')
    op.drop_index(op.f('ix_whatsapp_applications_name'), table_name='whatsapp_applications')
    op.drop_index(op.f('ix_whatsapp_applications_key'), table_name='whatsapp_applications')
    op.drop_index(op.f('ix_whatsapp_applications_enabled'), table_name='whatsapp_applications')
    op.drop_table('whatsapp_applications')
    # ### end Alembic commands ###
