"""whatsapp directory

Revision ID: 2a46410c6e53
Revises: 8f1ec17d90de
Create Date: 2026-07-13 16:22:18.266175
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '2a46410c6e53'
down_revision: Union[str, Sequence[str], None] = '8f1ec17d90de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_directory_contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_jid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_lid_jid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('token_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_checked_at', sa.DateTime(), nullable=True),
    sa.Column('token_issued_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'canonical_key', name='uq_whatsapp_contacts_account_key')
    )
    op.create_index(op.f('ix_whatsapp_directory_contacts_account_id'), 'whatsapp_directory_contacts', ['account_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_contacts_active'), 'whatsapp_directory_contacts', ['active'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_contacts_canonical_key'), 'whatsapp_directory_contacts', ['canonical_key'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_contacts_display_name'), 'whatsapp_directory_contacts', ['display_name'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_contacts_first_seen_at'), 'whatsapp_directory_contacts', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_contacts_last_seen_at'), 'whatsapp_directory_contacts', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_contacts_last_synced_at'), 'whatsapp_directory_contacts', ['last_synced_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_contacts_phone_jid'), 'whatsapp_directory_contacts', ['phone_jid'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_contacts_primary_lid_jid'), 'whatsapp_directory_contacts', ['primary_lid_jid'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_contacts_source'), 'whatsapp_directory_contacts', ['source'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_contacts_token_checked_at'), 'whatsapp_directory_contacts', ['token_checked_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_contacts_token_status'), 'whatsapp_directory_contacts', ['token_status'], unique=False)
    op.create_table('whatsapp_directory_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('jid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_jid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'jid', name='uq_whatsapp_directory_groups_account_jid')
    )
    op.create_index(op.f('ix_whatsapp_directory_groups_account_id'), 'whatsapp_directory_groups', ['account_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_groups_available'), 'whatsapp_directory_groups', ['available'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_groups_discovered_at'), 'whatsapp_directory_groups', ['discovered_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_groups_jid'), 'whatsapp_directory_groups', ['jid'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_groups_last_seen_at'), 'whatsapp_directory_groups', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_groups_last_synced_at'), 'whatsapp_directory_groups', ['last_synced_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_groups_name'), 'whatsapp_directory_groups', ['name'], unique=False)
    op.create_index(op.f('ix_whatsapp_directory_groups_owner_jid'), 'whatsapp_directory_groups', ['owner_jid'], unique=False)
    op.create_table('whatsapp_group_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('directory_group_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('member_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('member_jid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone_jid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lid_jid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('admin_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['whatsapp_directory_contacts.id'], ),
    sa.ForeignKeyConstraint(['directory_group_id'], ['whatsapp_directory_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('directory_group_id', 'member_key', name='uq_whatsapp_group_members_group_key')
    )
    op.create_index(op.f('ix_whatsapp_group_members_active'), 'whatsapp_group_members', ['active'], unique=False)
    op.create_index(op.f('ix_whatsapp_group_members_admin_role'), 'whatsapp_group_members', ['admin_role'], unique=False)
    op.create_index(op.f('ix_whatsapp_group_members_contact_id'), 'whatsapp_group_members', ['contact_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_group_members_directory_group_id'), 'whatsapp_group_members', ['directory_group_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_group_members_display_name'), 'whatsapp_group_members', ['display_name'], unique=False)
    op.create_index(op.f('ix_whatsapp_group_members_last_seen_at'), 'whatsapp_group_members', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_group_members_lid_jid'), 'whatsapp_group_members', ['lid_jid'], unique=False)
    op.create_index(op.f('ix_whatsapp_group_members_member_jid'), 'whatsapp_group_members', ['member_jid'], unique=False)
    op.create_index(op.f('ix_whatsapp_group_members_member_key'), 'whatsapp_group_members', ['member_key'], unique=False)
    op.create_index(op.f('ix_whatsapp_group_members_phone_jid'), 'whatsapp_group_members', ['phone_jid'], unique=False)
    op.create_table('whatsapp_identity_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('lid_jid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['whatsapp_directory_contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'lid_jid', name='uq_whatsapp_identity_aliases_account_lid')
    )
    op.create_index(op.f('ix_whatsapp_identity_aliases_account_id'), 'whatsapp_identity_aliases', ['account_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_identity_aliases_contact_id'), 'whatsapp_identity_aliases', ['contact_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_identity_aliases_last_seen_at'), 'whatsapp_identity_aliases', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_identity_aliases_lid_jid'), 'whatsapp_identity_aliases', ['lid_jid'], unique=False)
    op.create_index(op.f('ix_whatsapp_identity_aliases_source'), 'whatsapp_identity_aliases', ['source'], unique=False)
    op.add_column('whatsapp_groups', sa.Column('directory_group_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_whatsapp_groups_directory_group_id'), 'whatsapp_groups', ['directory_group_id'], unique=False)
    op.create_foreign_key('fk_whatsapp_groups_directory_group_id', 'whatsapp_groups', 'whatsapp_directory_groups', ['directory_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_whatsapp_groups_directory_group_id', 'whatsapp_groups', type_='foreignkey')
    op.drop_index(op.f('ix_whatsapp_groups_directory_group_id'), table_name='whatsapp_groups')
    op.drop_column('whatsapp_groups', 'directory_group_id')
    op.drop_index(op.f('ix_whatsapp_identity_aliases_source'), table_name='whatsapp_identity_aliases')
    op.drop_index(op.f('ix_whatsapp_identity_aliases_lid_jid'), table_name='whatsapp_identity_aliases')
    op.drop_index(op.f('ix_whatsapp_identity_aliases_last_seen_at'), table_name='whatsapp_identity_aliases')
    op.drop_index(op.f('ix_whatsapp_identity_aliases_contact_id'), table_name='whatsapp_identity_aliases')
    op.drop_index(op.f('ix_whatsapp_identity_aliases_account_id'), table_name='whatsapp_identity_aliases')
    op.drop_table('whatsapp_identity_aliases')
    op.drop_index(op.f('ix_whatsapp_group_members_phone_jid'), table_name='whatsapp_group_members')
    op.drop_index(op.f('ix_whatsapp_group_members_member_key'), table_name='whatsapp_group_members')
    op.drop_index(op.f('ix_whatsapp_group_members_member_jid'), table_name='whatsapp_group_members')
    op.drop_index(op.f('ix_whatsapp_group_members_lid_jid'), table_name='whatsapp_group_members')
    op.drop_index(op.f('ix_whatsapp_group_members_last_seen_at'), table_name='whatsapp_group_members')
    op.drop_index(op.f('ix_whatsapp_group_members_display_name'), table_name='whatsapp_group_members')
    op.drop_index(op.f('ix_whatsapp_group_members_directory_group_id'), table_name='whatsapp_group_members')
    op.drop_index(op.f('ix_whatsapp_group_members_contact_id'), table_name='whatsapp_group_members')
    op.drop_index(op.f('ix_whatsapp_group_members_admin_role'), table_name='whatsapp_group_members')
    op.drop_index(op.f('ix_whatsapp_group_members_active'), table_name='whatsapp_group_members')
    op.drop_table('whatsapp_group_members')
    op.drop_index(op.f('ix_whatsapp_directory_groups_owner_jid'), table_name='whatsapp_directory_groups')
    op.drop_index(op.f('ix_whatsapp_directory_groups_name'), table_name='whatsapp_directory_groups')
    op.drop_index(op.f('ix_whatsapp_directory_groups_last_synced_at'), table_name='whatsapp_directory_groups')
    op.drop_index(op.f('ix_whatsapp_directory_groups_last_seen_at'), table_name='whatsapp_directory_groups')
    op.drop_index(op.f('ix_whatsapp_directory_groups_jid'), table_name='whatsapp_directory_groups')
    op.drop_index(op.f('ix_whatsapp_directory_groups_discovered_at'), table_name='whatsapp_directory_groups')
    op.drop_index(op.f('ix_whatsapp_directory_groups_available'), table_name='whatsapp_directory_groups')
    op.drop_index(op.f('ix_whatsapp_directory_groups_account_id'), table_name='whatsapp_directory_groups')
    op.drop_table('whatsapp_directory_groups')
    op.drop_index(op.f('ix_whatsapp_directory_contacts_token_status'), table_name='whatsapp_directory_contacts')
    op.drop_index(op.f('ix_whatsapp_directory_contacts_token_checked_at'), table_name='whatsapp_directory_contacts')
    op.drop_index(op.f('ix_whatsapp_directory_contacts_source'), table_name='whatsapp_directory_contacts')
    op.drop_index(op.f('ix_whatsapp_directory_contacts_primary_lid_jid'), table_name='whatsapp_directory_contacts')
    op.drop_index(op.f('ix_whatsapp_directory_contacts_phone_jid'), table_name='whatsapp_directory_contacts')
    op.drop_index(op.f('ix_whatsapp_directory_contacts_last_synced_at'), table_name='whatsapp_directory_contacts')
    op.drop_index(op.f('ix_whatsapp_directory_contacts_last_seen_at'), table_name='whatsapp_directory_contacts')
    op.drop_index(op.f('ix_whatsapp_directory_contacts_first_seen_at'), table_name='whatsapp_directory_contacts')
    op.drop_index(op.f('ix_whatsapp_directory_contacts_display_name'), table_name='whatsapp_directory_contacts')
    op.drop_index(op.f('ix_whatsapp_directory_contacts_canonical_key'), table_name='whatsapp_directory_contacts')
    op.drop_index(op.f('ix_whatsapp_directory_contacts_active'), table_name='whatsapp_directory_contacts')
    op.drop_index(op.f('ix_whatsapp_directory_contacts_account_id'), table_name='whatsapp_directory_contacts')
    op.drop_table('whatsapp_directory_contacts')
    # ### end Alembic commands ###
