"""postgres master data baseline

Revision ID: 5749f5769e25
Revises: 
Create Date: 2026-07-13 15:09:22.774059
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '5749f5769e25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_active'), 'departments', ['active'], unique=False)
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=False)
    op.create_index(op.f('ix_departments_legacy_id'), 'departments', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_table('districts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_active'), 'districts', ['active'], unique=False)
    op.create_index(op.f('ix_districts_code'), 'districts', ['code'], unique=False)
    op.create_index(op.f('ix_districts_legacy_id'), 'districts', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=True)
    op.create_table('jobs',
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_task_id'), 'jobs', ['task_id'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('master_data_audits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_data_audits_action'), 'master_data_audits', ['action'], unique=False)
    op.create_index(op.f('ix_master_data_audits_actor'), 'master_data_audits', ['actor'], unique=False)
    op.create_index(op.f('ix_master_data_audits_created_at'), 'master_data_audits', ['created_at'], unique=False)
    op.create_index(op.f('ix_master_data_audits_entity_id'), 'master_data_audits', ['entity_id'], unique=False)
    op.create_index(op.f('ix_master_data_audits_entity_type'), 'master_data_audits', ['entity_type'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_created_at'), 'artifacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_artifacts_job_id'), 'artifacts', ['job_id'], unique=False)
    op.create_index(op.f('ix_artifacts_kind'), 'artifacts', ['kind'], unique=False)
    op.create_table('job_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_logs_created_at'), 'job_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_logs_job_id'), 'job_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_logs_level'), 'job_logs', ['level'], unique=False)
    op.create_table('tehsils',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'name', name='uq_tehsils_district_name'),
    sa.UniqueConstraint('id', 'district_id', name='uq_tehsils_id_district')
    )
    op.create_index(op.f('ix_tehsils_active'), 'tehsils', ['active'], unique=False)
    op.create_index(op.f('ix_tehsils_district_id'), 'tehsils', ['district_id'], unique=False)
    op.create_index(op.f('ix_tehsils_legacy_id'), 'tehsils', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_tehsils_name'), 'tehsils', ['name'], unique=False)
    op.create_table('wings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'department_id', 'name', name='uq_wings_scope_name'),
    sa.UniqueConstraint('id', 'district_id', 'department_id', name='uq_wings_id_scope')
    )
    op.create_index(op.f('ix_wings_active'), 'wings', ['active'], unique=False)
    op.create_index(op.f('ix_wings_code'), 'wings', ['code'], unique=False)
    op.create_index(op.f('ix_wings_department_id'), 'wings', ['department_id'], unique=False)
    op.create_index(op.f('ix_wings_district_id'), 'wings', ['district_id'], unique=False)
    op.create_index(op.f('ix_wings_legacy_id'), 'wings', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_wings_name'), 'wings', ['name'], unique=False)
    op.create_table('markazes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('wing_id', sa.Uuid(), nullable=False),
    sa.Column('tehsil_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['tehsil_id'], ['tehsils.id'], ),
    sa.ForeignKeyConstraint(['wing_id'], ['wings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'wing_id', 'tehsil_id', name='uq_markazes_id_scope'),
    sa.UniqueConstraint('wing_id', 'tehsil_id', 'name', name='uq_markazes_scope_name')
    )
    op.create_index(op.f('ix_markazes_active'), 'markazes', ['active'], unique=False)
    op.create_index(op.f('ix_markazes_legacy_id'), 'markazes', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_markazes_name'), 'markazes', ['name'], unique=False)
    op.create_index(op.f('ix_markazes_tehsil_id'), 'markazes', ['tehsil_id'], unique=False)
    op.create_index(op.f('ix_markazes_wing_id'), 'markazes', ['wing_id'], unique=False)
    op.create_table('officers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mobile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_mobile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('wing_id', sa.Uuid(), nullable=False),
    sa.Column('tehsil_id', sa.Uuid(), nullable=False),
    sa.Column('markaz_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['markaz_id', 'wing_id', 'tehsil_id'], ['markazes.id', 'markazes.wing_id', 'markazes.tehsil_id'], name='fk_officers_markaz_scope'),
    sa.ForeignKeyConstraint(['tehsil_id', 'district_id'], ['tehsils.id', 'tehsils.district_id'], name='fk_officers_tehsil_scope'),
    sa.ForeignKeyConstraint(['wing_id', 'district_id', 'department_id'], ['wings.id', 'wings.district_id', 'wings.department_id'], name='fk_officers_wing_scope'),
    sa.CheckConstraint("role IN ('aeo', 'ddeo')", name='ck_officers_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'wing_id', name='uq_officers_id_wing'),
    sa.UniqueConstraint('role', 'normalized_mobile', name='uq_officers_role_mobile')
    )
    op.create_index(op.f('ix_officers_active'), 'officers', ['active'], unique=False)
    op.create_index(op.f('ix_officers_department_id'), 'officers', ['department_id'], unique=False)
    op.create_index(op.f('ix_officers_district_id'), 'officers', ['district_id'], unique=False)
    op.create_index(op.f('ix_officers_legacy_id'), 'officers', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_officers_markaz_id'), 'officers', ['markaz_id'], unique=False)
    op.create_index(op.f('ix_officers_name'), 'officers', ['name'], unique=False)
    op.create_index(op.f('ix_officers_normalized_mobile'), 'officers', ['normalized_mobile'], unique=False)
    op.create_index(op.f('ix_officers_role'), 'officers', ['role'], unique=False)
    op.create_index(op.f('ix_officers_tehsil_id'), 'officers', ['tehsil_id'], unique=False)
    op.create_index(op.f('ix_officers_wing_id'), 'officers', ['wing_id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('emis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('wing_id', sa.Uuid(), nullable=False),
    sa.Column('tehsil_id', sa.Uuid(), nullable=False),
    sa.Column('markaz_id', sa.Uuid(), nullable=True),
    sa.Column('shift', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('school_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('school_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deos_wise', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_row_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['markaz_id', 'wing_id', 'tehsil_id'], ['markazes.id', 'markazes.wing_id', 'markazes.tehsil_id'], name='fk_schools_markaz_scope'),
    sa.ForeignKeyConstraint(['tehsil_id', 'district_id'], ['tehsils.id', 'tehsils.district_id'], name='fk_schools_tehsil_scope'),
    sa.ForeignKeyConstraint(['wing_id', 'district_id', 'department_id'], ['wings.id', 'wings.district_id', 'wings.department_id'], name='fk_schools_wing_scope'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'wing_id', name='uq_schools_id_wing')
    )
    op.create_index(op.f('ix_schools_active'), 'schools', ['active'], unique=False)
    op.create_index(op.f('ix_schools_department_id'), 'schools', ['department_id'], unique=False)
    op.create_index(op.f('ix_schools_district_id'), 'schools', ['district_id'], unique=False)
    op.create_index(op.f('ix_schools_emis'), 'schools', ['emis'], unique=True)
    op.create_index(op.f('ix_schools_legacy_id'), 'schools', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_schools_markaz_id'), 'schools', ['markaz_id'], unique=False)
    op.create_index(op.f('ix_schools_name'), 'schools', ['name'], unique=False)
    op.create_index(op.f('ix_schools_school_level'), 'schools', ['school_level'], unique=False)
    op.create_index(op.f('ix_schools_tehsil_id'), 'schools', ['tehsil_id'], unique=False)
    op.create_index(op.f('ix_schools_wing_id'), 'schools', ['wing_id'], unique=False)
    op.create_table('officer_jurisdictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('officer_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('wing_id', sa.Uuid(), nullable=False),
    sa.Column('tehsil_id', sa.Uuid(), nullable=False),
    sa.Column('markaz_id', sa.Uuid(), nullable=True),
    sa.Column('effective_from', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('effective_to', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['markaz_id', 'wing_id', 'tehsil_id'], ['markazes.id', 'markazes.wing_id', 'markazes.tehsil_id'], name='fk_jurisdictions_markaz_scope'),
    sa.ForeignKeyConstraint(['officer_id', 'wing_id'], ['officers.id', 'officers.wing_id'], name='fk_jurisdictions_officer_wing'),
    sa.ForeignKeyConstraint(['tehsil_id', 'district_id'], ['tehsils.id', 'tehsils.district_id'], name='fk_jurisdictions_tehsil_scope'),
    sa.ForeignKeyConstraint(['wing_id', 'district_id', 'department_id'], ['wings.id', 'wings.district_id', 'wings.department_id'], name='fk_jurisdictions_wing_scope'),
    sa.CheckConstraint("role IN ('aeo', 'ddeo')", name='ck_officer_jurisdictions_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('officer_id', 'wing_id', 'tehsil_id', 'markaz_id', name='uq_officer_jurisdictions_scope')
    )
    op.create_index(op.f('ix_officer_jurisdictions_active'), 'officer_jurisdictions', ['active'], unique=False)
    op.create_index(op.f('ix_officer_jurisdictions_department_id'), 'officer_jurisdictions', ['department_id'], unique=False)
    op.create_index(op.f('ix_officer_jurisdictions_district_id'), 'officer_jurisdictions', ['district_id'], unique=False)
    op.create_index(op.f('ix_officer_jurisdictions_legacy_id'), 'officer_jurisdictions', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_officer_jurisdictions_markaz_id'), 'officer_jurisdictions', ['markaz_id'], unique=False)
    op.create_index(op.f('ix_officer_jurisdictions_officer_id'), 'officer_jurisdictions', ['officer_id'], unique=False)
    op.create_index(op.f('ix_officer_jurisdictions_role'), 'officer_jurisdictions', ['role'], unique=False)
    op.create_index(op.f('ix_officer_jurisdictions_tehsil_id'), 'officer_jurisdictions', ['tehsil_id'], unique=False)
    op.create_index(op.f('ix_officer_jurisdictions_wing_id'), 'officer_jurisdictions', ['wing_id'], unique=False)
    op.create_table('school_heads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mobile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_mobile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_heads_active'), 'school_heads', ['active'], unique=False)
    op.create_index(op.f('ix_school_heads_legacy_id'), 'school_heads', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_school_heads_name'), 'school_heads', ['name'], unique=False)
    op.create_index(op.f('ix_school_heads_normalized_mobile'), 'school_heads', ['normalized_mobile'], unique=False)
    op.create_index(op.f('ix_school_heads_school_id'), 'school_heads', ['school_id'], unique=True)
    op.create_table('school_officer_overrides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legacy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('school_id', sa.Uuid(), nullable=False),
    sa.Column('officer_id', sa.Uuid(), nullable=False),
    sa.Column('wing_id', sa.Uuid(), nullable=False),
    sa.Column('effective_from', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('effective_to', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['officer_id', 'wing_id'], ['officers.id', 'officers.wing_id'], name='fk_overrides_officer_wing'),
    sa.ForeignKeyConstraint(['school_id', 'wing_id'], ['schools.id', 'schools.wing_id'], name='fk_overrides_school_wing'),
    sa.ForeignKeyConstraint(['wing_id'], ['wings.id'], ),
    sa.CheckConstraint("role IN ('aeo', 'ddeo')", name='ck_school_officer_overrides_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'officer_id', 'role', name='uq_school_officer_overrides')
    )
    op.create_index(op.f('ix_school_officer_overrides_active'), 'school_officer_overrides', ['active'], unique=False)
    op.create_index(op.f('ix_school_officer_overrides_legacy_id'), 'school_officer_overrides', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_school_officer_overrides_officer_id'), 'school_officer_overrides', ['officer_id'], unique=False)
    op.create_index(op.f('ix_school_officer_overrides_role'), 'school_officer_overrides', ['role'], unique=False)
    op.create_index(op.f('ix_school_officer_overrides_school_id'), 'school_officer_overrides', ['school_id'], unique=False)
    op.create_index(op.f('ix_school_officer_overrides_wing_id'), 'school_officer_overrides', ['wing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_officer_overrides_wing_id'), table_name='school_officer_overrides')
    op.drop_index(op.f('ix_school_officer_overrides_school_id'), table_name='school_officer_overrides')
    op.drop_index(op.f('ix_school_officer_overrides_role'), table_name='school_officer_overrides')
    op.drop_index(op.f('ix_school_officer_overrides_officer_id'), table_name='school_officer_overrides')
    op.drop_index(op.f('ix_school_officer_overrides_legacy_id'), table_name='school_officer_overrides')
    op.drop_index(op.f('ix_school_officer_overrides_active'), table_name='school_officer_overrides')
    op.drop_table('school_officer_overrides')
    op.drop_index(op.f('ix_school_heads_school_id'), table_name='school_heads')
    op.drop_index(op.f('ix_school_heads_normalized_mobile'), table_name='school_heads')
    op.drop_index(op.f('ix_school_heads_name'), table_name='school_heads')
    op.drop_index(op.f('ix_school_heads_legacy_id'), table_name='school_heads')
    op.drop_index(op.f('ix_school_heads_active'), table_name='school_heads')
    op.drop_table('school_heads')
    op.drop_index(op.f('ix_officer_jurisdictions_wing_id'), table_name='officer_jurisdictions')
    op.drop_index(op.f('ix_officer_jurisdictions_tehsil_id'), table_name='officer_jurisdictions')
    op.drop_index(op.f('ix_officer_jurisdictions_role'), table_name='officer_jurisdictions')
    op.drop_index(op.f('ix_officer_jurisdictions_officer_id'), table_name='officer_jurisdictions')
    op.drop_index(op.f('ix_officer_jurisdictions_markaz_id'), table_name='officer_jurisdictions')
    op.drop_index(op.f('ix_officer_jurisdictions_legacy_id'), table_name='officer_jurisdictions')
    op.drop_index(op.f('ix_officer_jurisdictions_district_id'), table_name='officer_jurisdictions')
    op.drop_index(op.f('ix_officer_jurisdictions_department_id'), table_name='officer_jurisdictions')
    op.drop_index(op.f('ix_officer_jurisdictions_active'), table_name='officer_jurisdictions')
    op.drop_table('officer_jurisdictions')
    op.drop_index(op.f('ix_schools_wing_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_tehsil_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_school_level'), table_name='schools')
    op.drop_index(op.f('ix_schools_name'), table_name='schools')
    op.drop_index(op.f('ix_schools_markaz_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_legacy_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_emis'), table_name='schools')
    op.drop_index(op.f('ix_schools_district_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_department_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_active'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_officers_wing_id'), table_name='officers')
    op.drop_index(op.f('ix_officers_tehsil_id'), table_name='officers')
    op.drop_index(op.f('ix_officers_role'), table_name='officers')
    op.drop_index(op.f('ix_officers_normalized_mobile'), table_name='officers')
    op.drop_index(op.f('ix_officers_name'), table_name='officers')
    op.drop_index(op.f('ix_officers_markaz_id'), table_name='officers')
    op.drop_index(op.f('ix_officers_legacy_id'), table_name='officers')
    op.drop_index(op.f('ix_officers_district_id'), table_name='officers')
    op.drop_index(op.f('ix_officers_department_id'), table_name='officers')
    op.drop_index(op.f('ix_officers_active'), table_name='officers')
    op.drop_table('officers')
    op.drop_index(op.f('ix_markazes_wing_id'), table_name='markazes')
    op.drop_index(op.f('ix_markazes_tehsil_id'), table_name='markazes')
    op.drop_index(op.f('ix_markazes_name'), table_name='markazes')
    op.drop_index(op.f('ix_markazes_legacy_id'), table_name='markazes')
    op.drop_index(op.f('ix_markazes_active'), table_name='markazes')
    op.drop_table('markazes')
    op.drop_index(op.f('ix_wings_name'), table_name='wings')
    op.drop_index(op.f('ix_wings_legacy_id'), table_name='wings')
    op.drop_index(op.f('ix_wings_district_id'), table_name='wings')
    op.drop_index(op.f('ix_wings_department_id'), table_name='wings')
    op.drop_index(op.f('ix_wings_code'), table_name='wings')
    op.drop_index(op.f('ix_wings_active'), table_name='wings')
    op.drop_table('wings')
    op.drop_index(op.f('ix_tehsils_name'), table_name='tehsils')
    op.drop_index(op.f('ix_tehsils_legacy_id'), table_name='tehsils')
    op.drop_index(op.f('ix_tehsils_district_id'), table_name='tehsils')
    op.drop_index(op.f('ix_tehsils_active'), table_name='tehsils')
    op.drop_table('tehsils')
    op.drop_index(op.f('ix_job_logs_level'), table_name='job_logs')
    op.drop_index(op.f('ix_job_logs_job_id'), table_name='job_logs')
    op.drop_index(op.f('ix_job_logs_created_at'), table_name='job_logs')
    op.drop_table('job_logs')
    op.drop_index(op.f('ix_artifacts_kind'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_job_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_created_at'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_master_data_audits_entity_type'), table_name='master_data_audits')
    op.drop_index(op.f('ix_master_data_audits_entity_id'), table_name='master_data_audits')
    op.drop_index(op.f('ix_master_data_audits_created_at'), table_name='master_data_audits')
    op.drop_index(op.f('ix_master_data_audits_actor'), table_name='master_data_audits')
    op.drop_index(op.f('ix_master_data_audits_action'), table_name='master_data_audits')
    op.drop_table('master_data_audits')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_task_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_index(op.f('ix_districts_legacy_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_code'), table_name='districts')
    op.drop_index(op.f('ix_districts_active'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_legacy_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_index(op.f('ix_departments_active'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
