"""whatsapp control plane

Revision ID: 8f1ec17d90de
Revises: 5749f5769e25
Create Date: 2026-07-13 15:53:33.682058
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '8f1ec17d90de'
down_revision: Union[str, Sequence[str], None] = '5749f5769e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('worker_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('command_subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('health_subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('qr_available', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_accounts_connected'), 'whatsapp_accounts', ['connected'], unique=False)
    op.create_index(op.f('ix_whatsapp_accounts_enabled'), 'whatsapp_accounts', ['enabled'], unique=False)
    op.create_index(op.f('ix_whatsapp_accounts_last_seen_at'), 'whatsapp_accounts', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_accounts_status'), 'whatsapp_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_whatsapp_accounts_worker_key'), 'whatsapp_accounts', ['worker_key'], unique=True)
    op.create_table('whatsapp_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_templates_category'), 'whatsapp_templates', ['category'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_enabled'), 'whatsapp_templates', ['enabled'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_key'), 'whatsapp_templates', ['key'], unique=True)
    op.create_table('whatsapp_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=True),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_activity_account_id'), 'whatsapp_activity', ['account_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_activity_created_at'), 'whatsapp_activity', ['created_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_activity_event_type'), 'whatsapp_activity', ['event_type'], unique=False)
    op.create_index(op.f('ix_whatsapp_activity_level'), 'whatsapp_activity', ['level'], unique=False)
    op.create_table('whatsapp_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('default_account_id', sa.Uuid(), nullable=False),
    sa.Column('send_delay_ms', sa.Integer(), nullable=False),
    sa.Column('acknowledgement_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('require_preview', sa.Boolean(), nullable=False),
    sa.Column('live_delivery_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_account_id'], ['whatsapp_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_settings_default_account_id'), 'whatsapp_settings', ['default_account_id'], unique=True)
    op.create_table('whatsapp_deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('wing_id', sa.Uuid(), nullable=True),
    sa.Column('recipient_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipient_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('queue_stream', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('queue_sequence', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('provider_result', sa.JSON(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'delivered', 'sent_pending_confirmation', 'failed', 'timed_out')", name='ck_whatsapp_deliveries_status'),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], ),
    sa.ForeignKeyConstraint(['wing_id'], ['wings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_subject')
    )
    op.create_index(op.f('ix_whatsapp_deliveries_account_id'), 'whatsapp_deliveries', ['account_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_deliveries_completed_at'), 'whatsapp_deliveries', ['completed_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_deliveries_queued_at'), 'whatsapp_deliveries', ['queued_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_deliveries_recipient_type'), 'whatsapp_deliveries', ['recipient_type'], unique=False)
    op.create_index(op.f('ix_whatsapp_deliveries_status'), 'whatsapp_deliveries', ['status'], unique=False)
    op.create_index(op.f('ix_whatsapp_deliveries_target'), 'whatsapp_deliveries', ['target'], unique=False)
    op.create_index(op.f('ix_whatsapp_deliveries_wing_id'), 'whatsapp_deliveries', ['wing_id'], unique=False)
    op.create_table('whatsapp_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('wing_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('jid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['whatsapp_accounts.id'], ),
    sa.ForeignKeyConstraint(['wing_id'], ['wings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'jid', name='uq_whatsapp_groups_account_jid')
    )
    op.create_index(op.f('ix_whatsapp_groups_account_id'), 'whatsapp_groups', ['account_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_groups_enabled'), 'whatsapp_groups', ['enabled'], unique=False)
    op.create_index(op.f('ix_whatsapp_groups_jid'), 'whatsapp_groups', ['jid'], unique=False)
    op.create_index(op.f('ix_whatsapp_groups_name'), 'whatsapp_groups', ['name'], unique=False)
    op.create_index(op.f('ix_whatsapp_groups_purpose'), 'whatsapp_groups', ['purpose'], unique=False)
    op.create_index(op.f('ix_whatsapp_groups_wing_id'), 'whatsapp_groups', ['wing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_groups_wing_id'), table_name='whatsapp_groups')
    op.drop_index(op.f('ix_whatsapp_groups_purpose'), table_name='whatsapp_groups')
    op.drop_index(op.f('ix_whatsapp_groups_name'), table_name='whatsapp_groups')
    op.drop_index(op.f('ix_whatsapp_groups_jid'), table_name='whatsapp_groups')
    op.drop_index(op.f('ix_whatsapp_groups_enabled'), table_name='whatsapp_groups')
    op.drop_index(op.f('ix_whatsapp_groups_account_id'), table_name='whatsapp_groups')
    op.drop_table('whatsapp_groups')
    op.drop_index(op.f('ix_whatsapp_deliveries_wing_id'), table_name='whatsapp_deliveries')
    op.drop_index(op.f('ix_whatsapp_deliveries_target'), table_name='whatsapp_deliveries')
    op.drop_index(op.f('ix_whatsapp_deliveries_status'), table_name='whatsapp_deliveries')
    op.drop_index(op.f('ix_whatsapp_deliveries_recipient_type'), table_name='whatsapp_deliveries')
    op.drop_index(op.f('ix_whatsapp_deliveries_queued_at'), table_name='whatsapp_deliveries')
    op.drop_index(op.f('ix_whatsapp_deliveries_completed_at'), table_name='whatsapp_deliveries')
    op.drop_index(op.f('ix_whatsapp_deliveries_account_id'), table_name='whatsapp_deliveries')
    op.drop_table('whatsapp_deliveries')
    op.drop_index(op.f('ix_whatsapp_settings_default_account_id'), table_name='whatsapp_settings')
    op.drop_table('whatsapp_settings')
    op.drop_index(op.f('ix_whatsapp_activity_level'), table_name='whatsapp_activity')
    op.drop_index(op.f('ix_whatsapp_activity_event_type'), table_name='whatsapp_activity')
    op.drop_index(op.f('ix_whatsapp_activity_created_at'), table_name='whatsapp_activity')
    op.drop_index(op.f('ix_whatsapp_activity_account_id'), table_name='whatsapp_activity')
    op.drop_table('whatsapp_activity')
    op.drop_index(op.f('ix_whatsapp_templates_key'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_enabled'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_category'), table_name='whatsapp_templates')
    op.drop_table('whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_accounts_worker_key'), table_name='whatsapp_accounts')
    op.drop_index(op.f('ix_whatsapp_accounts_status'), table_name='whatsapp_accounts')
    op.drop_index(op.f('ix_whatsapp_accounts_last_seen_at'), table_name='whatsapp_accounts')
    op.drop_index(op.f('ix_whatsapp_accounts_enabled'), table_name='whatsapp_accounts')
    op.drop_index(op.f('ix_whatsapp_accounts_connected'), table_name='whatsapp_accounts')
    op.drop_table('whatsapp_accounts')
    # ### end Alembic commands ###
