"""Native CRM complaint domain.

The package owns durable complaint identity and evidence records. Capture
providers such as WhatsApp may contribute documents, but do not own the case.
"""

from crm_domain.models import (
    ComplaintAuditEvent,
    ComplaintCategory,
    ComplaintCase,
    ComplaintDocument,
    ComplaintDocumentCaseLink,
    ComplaintFieldObservation,
    ComplaintMatch,
    ComplaintReply,
    ComplaintReplyRevision,
    CrmBulkOperationArtifact,
    CrmBulkOperationBatch,
    CrmBulkOperationItem,
    CrmComplaintClassification,
    CrmComplaintTag,
    CrmComplaintTagGroup,
    CrmComplaintTagLink,
    CrmDispatchArtifact,
    CrmDispatchBatch,
    CrmDispatchItem,
    CrmDispatchRule,
    CrmDispatchTarget,
    CrmUpwardSubmissionClaim,
    CrmOfficialLetter,
    CrmOfficialLetterArtifact,
    CrmOfficialLetterSettings,
    CrmOfficialLetterSignatureProfile,
    CrmOfficialLetterTemplate,
    CrmPaperlessStatusSync,
    CrmSpreadsheetIntakeBatch,
    CrmSpreadsheetIntakeRow,
    CrmPromptProfile,
    CrmPromptProfileVersion,
    CrmReplyContextExample,
    CrmTaxonomySuggestion,
    ComplaintSubcategory,
    DocumentExtraction,
    PaperlessPublication,
)

__all__ = [
    "ComplaintAuditEvent",
    "ComplaintCategory",
    "ComplaintCase",
    "ComplaintDocument",
    "ComplaintDocumentCaseLink",
    "ComplaintFieldObservation",
    "ComplaintMatch",
    "ComplaintReply",
    "ComplaintReplyRevision",
    "CrmBulkOperationArtifact",
    "CrmBulkOperationBatch",
    "CrmBulkOperationItem",
    "CrmComplaintClassification",
    "CrmComplaintTag",
    "CrmComplaintTagGroup",
    "CrmComplaintTagLink",
    "CrmDispatchArtifact",
    "CrmDispatchBatch",
    "CrmDispatchItem",
    "CrmDispatchRule",
    "CrmDispatchTarget",
    "CrmUpwardSubmissionClaim",
    "CrmOfficialLetter",
    "CrmOfficialLetterArtifact",
    "CrmOfficialLetterSettings",
    "CrmOfficialLetterSignatureProfile",
    "CrmOfficialLetterTemplate",
    "CrmPaperlessStatusSync",
    "CrmSpreadsheetIntakeBatch",
    "CrmSpreadsheetIntakeRow",
    "CrmPromptProfile",
    "CrmPromptProfileVersion",
    "CrmReplyContextExample",
    "CrmTaxonomySuggestion",
    "ComplaintSubcategory",
    "DocumentExtraction",
    "PaperlessPublication",
]
