export type AeoOption = {
  name: string;
  tehsil: string;
  markaz: string;
  wing: string;
};

export const aeoOptions = [
  { name: "Muhammad Aamir Akram", tehsil: "Raiwind", markaz: "Raiwind", wing: "MEE" },
  { name: "Waleed Ashraf", tehsil: "Raiwind", markaz: "Chung", wing: "MEE" },
  { name: "Muhammad Imran", tehsil: "City", markaz: "Samanabad", wing: "MEE" },
  { name: "Umar Farooq", tehsil: "Model Town", markaz: "Township", wing: "MEE" },
  { name: "Shujah Ur Rehman", tehsil: "Cantt", markaz: "Bhangali", wing: "MEE" },
  { name: "Hamza Ali Butt", tehsil: "Shalimar", markaz: "Bhaseen", wing: "MEE" },
  { name: "Gulbaz Ahsan Shabir", tehsil: "Shalimar", markaz: "Fateh Garh", wing: "MEE" },
  { name: "Muhammad Awais", tehsil: "Model Town", markaz: "Badoki", wing: "MEE" },
  { name: "Muhammad Ahmad", tehsil: "City", markaz: "Niaz Baig", wing: "MEE" },
  { name: "Adeel Zulfiqar", tehsil: "Raiwind", markaz: "Paji", wing: "MEE" },
  { name: "Muhammad Usman Liaqat", tehsil: "City", markaz: "Naulakha", wing: "MEE" },
  { name: "Waqar ul Nisa", tehsil: "Model Town", markaz: "Gulberg", wing: "MEE" },
  { name: "Muhammad Zeeshan", tehsil: "Cantt", markaz: "Cantt", wing: "MEE" },
  { name: "Umair Fazal", tehsil: "City", markaz: "Shahdara", wing: "MEE" },
  { name: "Rukhshanda", tehsil: "Model Town", markaz: "Kamahan", wing: "MEE" },
  { name: "Anas Ahmad", tehsil: "Cantt", markaz: "Bedian", wing: "MEE" },
  { name: "Bilal Adeel Kazmi", tehsil: "Shalimar", markaz: "Baghbanpura", wing: "MEE" },
  { name: "Hafiz Muhammad Awais", tehsil: "City", markaz: "Lahore Khas", wing: "MEE" },
  { name: "Muhammad Zia Ur Rehman", tehsil: "Shalimar", markaz: "Minhala", wing: "MEE" },
  { name: "Imran Ali", tehsil: "Model Town", markaz: "Kot Lakhpat", wing: "MEE" },
  { name: "Sundas Jabeen", tehsil: "Cantt", markaz: "Manga", wing: "MEE" },
  { name: "Shumaila Kaleem", tehsil: "Shalimar", markaz: "Gharhi Shahu", wing: "MEE" },
  { name: "Arshad Saeed Khan", tehsil: "City", markaz: "Sanda", wing: "MEE" },
  { name: "Junaid Ahmad", tehsil: "Raiwind", markaz: "Sunder", wing: "MEE" },
  { name: "Ajmal Raza", tehsil: "Model Town", markaz: "Kahna", wing: "MEE" },
  { name: "Sofia Noreen", tehsil: "Cantt", markaz: "Heir", wing: "MEE" },
  { name: "Shumaila Hameed", tehsil: "Model Town", markaz: "Kahna", wing: "WEE" },
  { name: "Sehrish Saleem", tehsil: "Model Town", markaz: "Nishter", wing: "WEE" },
  { name: "Anum Zafar", tehsil: "Cantt", markaz: "Heir", wing: "WEE" },
  { name: "Rabia Pervaiz Awan", tehsil: "Shalimar", markaz: "Bhaseen", wing: "WEE" },
  { name: "Shamsa Younas", tehsil: "Raiwind", markaz: "Chung", wing: "WEE" },
  { name: "Sadaf Amin", tehsil: "Shalimar", markaz: "Fateh Garh", wing: "WEE" },
  { name: "Tahira Nazir", tehsil: "Shalimar", markaz: "Baghbanpura", wing: "WEE" },
  { name: "Zunera Fatima", tehsil: "City", markaz: "Shahdara", wing: "WEE" },
  { name: "Asma Shahid", tehsil: "City", markaz: "Sanda", wing: "WEE" },
  { name: "Sundas Fatima", tehsil: "City", markaz: "Lahore Khas", wing: "WEE" },
  { name: "Neelam Arshad", tehsil: "Shalimar", markaz: "Shalimar", wing: "WEE" },
  { name: "Iqra Noreen Ashraf", tehsil: "Raiwind", markaz: "Pajjian", wing: "WEE" },
  { name: "Anum Waheed", tehsil: "Cantt", markaz: "Hadiara", wing: "WEE" },
  { name: "Safana Dogar", tehsil: "City", markaz: "Naulakha", wing: "WEE" },
  { name: "Iram Qadir Bakhsh", tehsil: "Model Town", markaz: "Kamahan", wing: "WEE" },
  { name: "Hafiza Kanwal Iftikhar", tehsil: "Model Town", markaz: "Ichra", wing: "WEE" },
  { name: "Shumaila Ramzan", tehsil: "Model Town", markaz: "Model Town", wing: "WEE" },
  { name: "Naila Parveen", tehsil: "City", markaz: "Niaz Baig", wing: "WEE" },
  { name: "Samra Tahseen", tehsil: "Shalimar", markaz: "Jallo", wing: "WEE" },
  { name: "Saba Ehsan", tehsil: "Cantt", markaz: "Barki", wing: "WEE" },
  { name: "Iqra Mubeen", tehsil: "Cantt", markaz: "Bhangali", wing: "WEE" },
  { name: "Ammara Shaukat", tehsil: "Cantt", markaz: "Cantt", wing: "WEE" },
  { name: "Sharmeen Hanif", tehsil: "Raiwind", markaz: "Manga", wing: "WEE" },
  { name: "Naila Ashraf", tehsil: "Raiwind", markaz: "Sunder", wing: "WEE" },
  { name: "Hafiza Samreen Kousar", tehsil: "Raiwind", markaz: "Raiwind", wing: "WEE" },
] as const satisfies readonly AeoOption[];
