from __future__ import annotations

from complaints_manager.core.command_model import ArgField, CommandSpec, EnvField, Option


COMMANDS: tuple[CommandSpec, ...] = (
    CommandSpec(
        id="crm_filter_excel_duplicates",
        system_id="crm",
        title="Filter CRM Sheet Duplicates",
        group="Intake",
        summary="Filter CRM Excel/CSV rows against Paperless and split fresh/submitted/uploaded records.",
        script="filter_crm_excel_duplicates.py",
        arg_fields=(
            ArgField("input_file", "CRM sheet file", "--input-file", "", "file"),
            ArgField("input_dir", "Sheet folder", "--input-dir", "phase1-crm/unprocessed-crm/sheets", "path"),
            ArgField(
                "output_dir",
                "Filtered output folder",
                "--output-dir",
                "phase1-crm/unprocessed-crm/filtered",
                "path",
            ),
        ),
    ),
    CommandSpec(
        id="crm_filter_pdf_duplicates",
        system_id="crm",
        title="Filter CRM PDF Duplicates",
        group="Intake",
        summary="OCR CRM PDFs, compare them against Paperless CRM complaints, and split fresh/submitted/uploaded/manual-review files.",
        script="filter_crm_pdf_duplicates.py",
        arg_fields=(
            ArgField("input_dir", "Raw complaint PDF folder", "--input-dir", "phase1-crm/unprocessed-crm/pdf", "path"),
            ArgField(
                "output_dir",
                "Filtered output folder",
                "--output-dir",
                "phase1-crm/unprocessed-crm/filtered",
                "path",
            ),
            ArgField("db", "OCR cache DB", "--db", "crm-cache.sqlite", "file"),
            ArgField(
                "skip_paperless_refresh",
                "Use existing Paperless cache",
                "--skip-paperless-refresh",
                "false",
                "bool_flag",
            ),
            ArgField("paperless_limit", "Paperless index limit", "--paperless-limit", "", "int"),
        ),
    ),
    CommandSpec(
        id="crm_prepare_duplicate_notices",
        system_id="crm",
        title="Prepare Duplicate Notice Lists",
        group="Intake",
        summary="Create WhatsApp notice CSVs from filtered submitted and not-relevant CRM sheet rows.",
        script="crm_duplicate_notices.py",
        args=("prepare",),
        arg_fields=(
            ArgField("input_file", "Original CRM sheet file", "--input-file", "", "file"),
            ArgField(
                "output_dir",
                "Filtered output folder",
                "--output-dir",
                "phase1-crm/unprocessed-crm/filtered",
                "path",
            ),
            ArgField(
                "status",
                "Notice type",
                "--status",
                "all",
                "select",
                options=(
                    Option("all", "Submitted + Not Relevant"),
                    Option("submitted", "Submitted only"),
                    Option("not-relevant", "Not Relevant only"),
                ),
            ),
            ArgField("dispatch_dir", "Notice CSV folder", "--dispatch-dir", "", "path"),
        ),
    ),
    CommandSpec(
        id="crm_send_duplicate_notices",
        system_id="crm",
        title="Send Duplicate Notices",
        group="Intake",
        summary="Send WhatsApp notices for filtered submitted and not-relevant CRM sheet rows.",
        script="crm_duplicate_notices.py",
        args=("send",),
        arg_fields=(
            ArgField("input_file", "Original CRM sheet file", "--input-file", "", "file"),
            ArgField(
                "output_dir",
                "Filtered output folder",
                "--output-dir",
                "phase1-crm/unprocessed-crm/filtered",
                "path",
            ),
            ArgField(
                "status",
                "Notice type",
                "--status",
                "all",
                "select",
                options=(
                    Option("all", "Submitted + Not Relevant"),
                    Option("submitted", "Submitted only"),
                    Option("not-relevant", "Not Relevant only"),
                ),
            ),
            ArgField("dispatch_dir", "Notice CSV folder", "--dispatch-dir", "", "path"),
            ArgField("dispatch_csv", "Specific notice CSV", "--dispatch-csv", "", "file"),
            ArgField("dry_run", "Dry run", "--dry-run", "false", "bool_flag"),
        ),
        confirm_label="Queues WhatsApp status notices to citizens from filtered duplicate rows",
    ),
    CommandSpec(
        id="crm_excel_rows_to_pdfs",
        system_id="crm",
        title="Convert Sheet Rows to PDFs",
        group="Intake",
        summary="Convert CRM complaint rows from Excel or CSV files into complaint PDFs for the CRM intake folder.",
        script="convert_excel_rows_to_pdfs.py",
        arg_fields=(
            ArgField(
                "input_dir",
                "Sheet folder",
                "--input-dir",
                "phase1-crm/unprocessed-crm/sheets",
                "path",
            ),
            ArgField("output_dir", "PDF output folder", "--output-dir", "crm-main-complaints", "path"),
            ArgField("overwrite", "Overwrite existing PDFs", "--overwrite", "false", "bool_flag"),
        ),
    ),
    CommandSpec(
        id="crm_ingest_pending",
        system_id="crm",
        title="Prepare CRM Pending Upload",
        group="Intake",
        summary="Build Paperless-ready Pending artifacts from filtered fresh CRM PDFs using the OCR cache.",
        script="prepare_crm_upload.py",
        arg_fields=(
            ArgField(
                "input_dir",
                "Filtered fresh number-found PDF folder",
                "--input-dir",
                "phase1-crm/unprocessed-crm/filtered/fresh/number-found",
                "path",
            ),
            ArgField("artifact_dir", "Artifact staging folder", "--artifact-dir", "artifacts/crm-pending", "path"),
            ArgField("crm_cache_db", "OCR cache DB", "--crm-cache-db", "crm-cache.sqlite", "file"),
            ArgField("cache_only", "Use OCR cache only", "--cache-only", "true", "bool_flag"),
            ArgField(
                "allow_placeholder_number",
                "Upload with placeholder number",
                "--allow-placeholder-number",
                "true",
                "bool_flag",
            ),
            ArgField("clear_artifact_dir", "Clear artifact folder first", "--clear-artifact-dir", "true", "bool_flag"),
        ),
        confirm_label="Prepares filtered CRM PDFs for Pending upload",
    ),
    CommandSpec(
        id="crm_review_number_missing",
        system_id="crm",
        title="Review Number-Missing CRM PDFs",
        group="Intake",
        summary="Open the number-missing PDF folder and auto-populate manual override files with OCR candidate values for review.",
        script="review_crm_number_missing.py",
        arg_fields=(
            ArgField(
                "review_dir",
                "Number-missing review folder",
                "--review-dir",
                "phase1-crm/unprocessed-crm/filtered/fresh/number-missing",
                "path",
            ),
            ArgField("open_folder", "Open review folder", "--open-folder", "true", "bool_flag"),
        ),
    ),
    CommandSpec(
        id="crm_prepare_reviewed_number_missing",
        system_id="crm",
        title="Prepare Reviewed Number-Missing Upload",
        group="Intake",
        summary="Build Paperless-ready Pending artifacts from number-missing PDFs after crm-complaint-overrides.json has been reviewed.",
        script="prepare_crm_upload.py",
        arg_fields=(
            ArgField(
                "input_dir",
                "Reviewed number-missing PDF folder",
                "--input-dir",
                "phase1-crm/unprocessed-crm/filtered/fresh/number-missing",
                "path",
            ),
            ArgField("artifact_dir", "Artifact staging folder", "--artifact-dir", "artifacts/crm-pending", "path"),
            ArgField("crm_cache_db", "OCR cache DB", "--crm-cache-db", "crm-cache.sqlite", "file"),
            ArgField("cache_only", "Use reviewed overrides/cache only", "--cache-only", "true", "bool_flag"),
            ArgField("clear_artifact_dir", "Clear artifact folder first", "--clear-artifact-dir", "true", "bool_flag"),
        ),
        confirm_label="Prepares reviewed number-missing CRM PDFs for Pending upload",
    ),
    CommandSpec(
        id="crm_upload_pending",
        system_id="crm",
        title="Upload CRM Pending PDFs",
        group="Intake",
        summary="Upload the already staged CRM Pending artifacts to Paperless.",
        script="main.py",
        args=("paperless",),
        env_fields=(
            EnvField("PAPERLESS_MAX_CASES", "Max Paperless cases", "", "int"),
            EnvField("PAPERLESS_DRY_RUN", "Dry run", "false", "bool"),
        ),
        arg_fields=(
            ArgField("artifact_dir", "Artifact upload folder", "--artifact-dir", "artifacts/crm-pending", "path"),
        ),
        confirm_label="Uploads staged CRM Pending artifacts to Paperless",
    ),
    CommandSpec(
        id="crm_ingest_not_relevant",
        system_id="crm",
        title="Prepare CRM Not Relevant Upload",
        group="Intake",
        summary="Build Paperless-ready Not Relevant artifacts from selected CRM PDFs using the OCR cache.",
        script="prepare_crm_upload.py",
        args=("--status", "Not Relevant"),
        arg_fields=(
            ArgField("input_dir", "Complaint PDF folder", "--input-dir", "crm-not-relevant", "path"),
            ArgField(
                "artifact_dir",
                "Artifact staging folder",
                "--artifact-dir",
                "artifacts/crm-not-relevant",
                "path",
            ),
            ArgField("crm_cache_db", "OCR cache DB", "--crm-cache-db", "crm-cache.sqlite", "file"),
            ArgField("cache_only", "Use OCR cache only", "--cache-only", "true", "bool_flag"),
            ArgField("clear_artifact_dir", "Clear artifact folder first", "--clear-artifact-dir", "true", "bool_flag"),
        ),
        confirm_label="Prepares CRM Not Relevant artifacts for upload",
    ),
    CommandSpec(
        id="crm_upload_not_relevant",
        system_id="crm",
        title="Upload CRM Not Relevant PDFs",
        group="Intake",
        summary="Upload the already staged CRM Not Relevant artifacts to Paperless.",
        script="main.py",
        args=("paperless",),
        env_fields=(
            EnvField("PAPERLESS_MAX_CASES", "Max Paperless cases", "", "int"),
            EnvField("PAPERLESS_DRY_RUN", "Dry run", "false", "bool"),
        ),
        arg_fields=(
            ArgField(
                "artifact_dir",
                "Artifact upload folder",
                "--artifact-dir",
                "artifacts/crm-not-relevant",
                "path",
            ),
        ),
        confirm_label="Uploads staged CRM Not Relevant artifacts to Paperless",
    ),
    CommandSpec(
        id="crm_patch_paperless",
        system_id="crm",
        title="Patch Paperless Metadata",
        group="Paperless",
        summary="Update metadata and custom fields for existing CRM Paperless documents.",
        script="main.py",
        args=("paperless-patch",),
        env_fields=(
            EnvField("PAPERLESS_MAX_CASES", "Max cases", "", "int"),
            EnvField("PAPERLESS_DRY_RUN", "Dry run", "false", "bool"),
        ),
        arg_fields=(
            ArgField("artifact_dir", "Artifact folder", "--artifact-dir", "artifacts/crm-pending", "path"),
        ),
        confirm_label="Patches metadata on existing Paperless documents",
    ),
    CommandSpec(
        id="crm_generate_letters",
        system_id="crm",
        title="Generate Inquiry Letters",
        group="Letters",
        summary="Generate ODT inquiry letters from Paperless complaint metadata.",
        script="generate_letters.py",
    ),
    CommandSpec(
        id="crm_convert_letters",
        system_id="crm",
        title="Convert Letters to PDF",
        group="Letters",
        summary="Convert generated ODT letters to PDFs with LibreOffice.",
        raw_command=(
            "zsh",
            "-lc",
            "libreoffice --headless --convert-to pdf generated_letters/*.odt --outdir generated_letters/",
        ),
    ),
    CommandSpec(
        id="crm_prepare_compliance_folders",
        system_id="crm",
        title="Prepare Pending Compliance Folders",
        group="Compliances",
        summary="Get pending CRM complaints from Paperless, create compliance folders, and optionally place LLM prompt files beside each ODT.",
        script="generate_crm_compliance_folders.py",
        env_fields=(
            EnvField("CRM_COMPLIANCE_SAMPLE_DIR", "Sample folder", "crm-compliances/pending/sample", "path"),
            EnvField("CRM_COMPLIANCE_PENDING_DIR", "Pending folder", "crm-compliances/pending", "path"),
            EnvField("NOCODB_URL", "NocoDB URL", "https://crm-replies.lab.internal", "text"),
            EnvField("NOCODB_EMAIL", "NocoDB email", "ahmadkakarr@gmail.com", "text"),
            EnvField("NOCODB_PASSWORD", "NocoDB password", "", "text"),
            EnvField("NOCODB_BASE_TITLE", "NocoDB base", "CRM Reply Knowledge Base", "text"),
        ),
        arg_fields=(
            ArgField("sample_dir", "Sample folder", "--sample-dir", "", "hidden_env:CRM_COMPLIANCE_SAMPLE_DIR"),
            ArgField("pending_dir", "Pending folder", "--pending-dir", "", "hidden_env:CRM_COMPLIANCE_PENDING_DIR"),
            ArgField("--limit", "Limit", "--limit", "", "int"),
            ArgField("--dry-run", "Dry run", "--dry-run", "false", "bool_flag"),
            ArgField("--overwrite", "Overwrite existing folders", "--overwrite", "false", "bool_flag"),
            ArgField("build_context_packs", "Build LLM prompt files", "--build-context-packs", "true", "bool_flag"),
            ArgField("context_top_examples", "Top examples", "--context-top-examples", "5", "int"),
            ArgField(
                "include_unverified_policy",
                "Include unverified policy rows",
                "--include-unverified-policy",
                "true",
                "bool_flag",
            ),
            ArgField("nocodb_url", "NocoDB URL", "--nocodb-url", "", "hidden_env:NOCODB_URL"),
            ArgField("nocodb_email", "NocoDB email", "--nocodb-email", "", "hidden_env:NOCODB_EMAIL"),
            ArgField("nocodb_password", "NocoDB password", "--nocodb-password", "", "hidden_env:NOCODB_PASSWORD"),
            ArgField("nocodb_base", "NocoDB base", "--nocodb-base", "", "hidden_env:NOCODB_BASE_TITLE"),
        ),
    ),
    CommandSpec(
        id="crm_apply_deo_replies",
        system_id="crm",
        title="Apply DEO Replies",
        group="Compliances",
        summary="Fill DEO Report remarks from a two-column complaint number and reply file.",
        script="apply_deo_replies.py",
        arg_fields=(
            ArgField(
                "replies_file",
                "Replies file",
                "--replies-file",
                "crm-compliances/pending/pending-complaint-replies-two-columns.csv",
                "file",
            ),
            ArgField(
                "pending_dir",
                "Pending folder",
                "--pending-dir",
                "crm-compliances/pending",
                "path",
            ),
            ArgField("dry_run", "Dry run", "--dry-run", "false", "bool_flag"),
            ArgField("no_backup", "Do not create backups", "--no-backup", "false", "bool_flag"),
        ),
        confirm_label="Updates DEO Report ODT files in pending compliance folders",
    ),
    CommandSpec(
        id="crm_upload_compliances",
        system_id="crm",
        title="Upload Compliances",
        group="Compliances",
        summary="Upload DEO/DDEO/institute compliance reports to Paperless.",
        script="upload_compliances.py",
        arg_fields=(
            ArgField("compliances_dir", "Compliance folder", "--compliances-dir", "crm-compliances/pending", "path"),
            ArgField("dispatch_csv", "Dispatch CSV", "--dispatch-csv", "crm-compliances/crm-dispatch-list.csv", "file"),
            ArgField(
                "no_update_dispatch_list",
                "Do not update dispatch CSV",
                "--no-update-dispatch-list",
                "false",
                "bool_flag",
            ),
        ),
    ),
    CommandSpec(
        id="crm_sync_reply_knowledge",
        system_id="crm",
        title="Sync Reply Knowledge",
        group="Replies",
        summary="Read manually drafted DEO report remarks from pending compliance folders and sync them into NocoDB.",
        script="sync_crm_reply_knowledge.py",
        env_fields=(
            EnvField("NOCODB_URL", "NocoDB URL", "https://crm-replies.lab.internal", "text"),
            EnvField("NOCODB_EMAIL", "NocoDB email", "ahmadkakarr@gmail.com", "text"),
            EnvField("NOCODB_PASSWORD", "NocoDB password", "", "text"),
            EnvField("NOCODB_BASE_TITLE", "NocoDB base", "CRM Reply Knowledge Base", "text"),
        ),
        arg_fields=(
            ArgField("pending_dir", "Pending compliance folder", "--pending-dir", "crm-compliances/pending", "path"),
            ArgField("clear", "Clear NocoDB tables first", "--clear", "true", "bool_flag"),
            ArgField("nocodb_url", "NocoDB URL", "--nocodb-url", "", "hidden_env:NOCODB_URL"),
            ArgField("nocodb_email", "NocoDB email", "--nocodb-email", "", "hidden_env:NOCODB_EMAIL"),
            ArgField("nocodb_password", "NocoDB password", "--nocodb-password", "", "hidden_env:NOCODB_PASSWORD"),
            ArgField("nocodb_base", "NocoDB base", "--nocodb-base", "", "hidden_env:NOCODB_BASE_TITLE"),
        ),
        confirm_label="Clears and repopulates CRM reply knowledge tables in NocoDB",
    ),
    CommandSpec(
        id="crm_sync_reply_knowledge_paperless",
        system_id="crm",
        title="Sync Reply Knowledge From Paperless",
        group="Replies",
        summary="Read submitted CRM main complaints and linked DEO reports from Paperless, classify them, and upsert the reply knowledgebase in NocoDB.",
        script="sync_crm_reply_knowledge_from_paperless.py",
        env_fields=(
            EnvField("NOCODB_URL", "NocoDB URL", "https://crm-replies.lab.internal", "text"),
            EnvField("NOCODB_EMAIL", "NocoDB email", "ahmadkakarr@gmail.com", "text"),
            EnvField("NOCODB_PASSWORD", "NocoDB password", "", "text"),
            EnvField("NOCODB_BASE_TITLE", "NocoDB base", "CRM Reply Knowledge Base", "text"),
        ),
        arg_fields=(
            ArgField("status", "Paperless status", "--status", "Submitted", "text"),
            ArgField("limit", "Limit", "--limit", "", "int"),
            ArgField("min_reply_chars", "Minimum reply chars", "--min-reply-chars", "120", "int"),
            ArgField("dry_run", "Dry run", "--dry-run", "false", "bool_flag"),
            ArgField("clear", "Clear NocoDB tables first", "--clear", "false", "bool_flag"),
            ArgField("nocodb_url", "NocoDB URL", "--nocodb-url", "", "hidden_env:NOCODB_URL"),
            ArgField("nocodb_email", "NocoDB email", "--nocodb-email", "", "hidden_env:NOCODB_EMAIL"),
            ArgField("nocodb_password", "NocoDB password", "--nocodb-password", "", "hidden_env:NOCODB_PASSWORD"),
            ArgField("nocodb_base", "NocoDB base", "--nocodb-base", "", "hidden_env:NOCODB_BASE_TITLE"),
        ),
        confirm_label="Updates CRM reply knowledge in NocoDB from Paperless submitted reports",
    ),
    CommandSpec(
        id="crm_build_reply_context",
        system_id="crm",
        title="Build Reply Context Packs",
        group="Replies",
        summary="Build compact JSON and prompt text packs from NocoDB for LLM-assisted CRM reply drafting.",
        script="build_crm_reply_context.py",
        env_fields=(
            EnvField("NOCODB_URL", "NocoDB URL", "https://crm-replies.lab.internal", "text"),
            EnvField("NOCODB_EMAIL", "NocoDB email", "ahmadkakarr@gmail.com", "text"),
            EnvField("NOCODB_PASSWORD", "NocoDB password", "", "text"),
            EnvField("NOCODB_BASE_TITLE", "NocoDB base", "CRM Reply Knowledge Base", "text"),
        ),
        arg_fields=(
            ArgField("pending_dir", "Pending compliance folder", "--pending-dir", "crm-compliances/pending", "path"),
            ArgField("output_dir", "Context output folder", "--output-dir", "crm-reply-context-packs", "path"),
            ArgField(
                "output_mode",
                "Output mode",
                "--output-mode",
                "complaint-folder",
                "select",
                options=(
                    Option("complaint-folder", "Complaint folders"),
                    Option("central", "Central folder"),
                ),
            ),
            ArgField("complaint_number", "Only complaint number", "--complaint-number", "", "text"),
            ArgField("top_examples", "Top examples", "--top-examples", "5", "int"),
            ArgField(
                "include_unverified_policy",
                "Include unverified policy rows",
                "--include-unverified-policy",
                "false",
                "bool_flag",
            ),
            ArgField("write_prompt_text", "Write prompt text files", "--write-prompt-text", "true", "bool_flag"),
            ArgField("nocodb_url", "NocoDB URL", "--nocodb-url", "", "hidden_env:NOCODB_URL"),
            ArgField("nocodb_email", "NocoDB email", "--nocodb-email", "", "hidden_env:NOCODB_EMAIL"),
            ArgField("nocodb_password", "NocoDB password", "--nocodb-password", "", "hidden_env:NOCODB_PASSWORD"),
            ArgField("nocodb_base", "NocoDB base", "--nocodb-base", "", "hidden_env:NOCODB_BASE_TITLE"),
        ),
    ),
    CommandSpec(
        id="crm_preview_compliances",
        system_id="crm",
        title="Preview Compliance Dispatch",
        group="Compliances",
        summary="Prepare the exact compliance PDFs and an HTML preview without sending WhatsApp jobs.",
        script="send_compliances.py",
        args=("--preview",),
        arg_fields=(
            ArgField("preview_date", "Date", "--date", "", "date"),
            ArgField("preview_limit", "Limit", "--limit", "", "int"),
            ArgField(
                "preview_csv",
                "Dispatch CSV",
                "--csv",
                "crm-compliances/crm-dispatch-list.csv",
                "file",
            ),
            ArgField(
                "attachment_mode",
                "PDF delivery",
                "--attachment-mode",
                "combined",
                "select",
                options=(
                    Option("combined", "One combined PDF"),
                    Option("separate", "Separate PDFs"),
                ),
            ),
        ),
    ),
    CommandSpec(
        id="crm_open_latest_compliance_preview",
        system_id="crm",
        title="Open Latest Dispatch Preview",
        group="Compliances",
        summary="Open the latest CRM compliance dispatch preview in the browser.",
        script="open_latest_compliance_dispatch_preview.py",
    ),
    CommandSpec(
        id="crm_send_compliances",
        system_id="crm",
        title="Dispatch Compliances",
        group="Compliances",
        summary="Dispatch compliance reports through WhatsApp jobs and audit deliveries.",
        script="send_compliances.py",
        arg_fields=(
            ArgField("--date", "Date", "--date", "", "date"),
            ArgField("send_at", "Send at", "--send-at", "", "datetime"),
            ArgField("--limit", "Limit", "--limit", "", "int"),
            ArgField("--csv", "Dispatch CSV", "--csv", "crm-compliances/crm-dispatch-list.csv", "file"),
            ArgField(
                "attachment_mode",
                "PDF delivery",
                "--attachment-mode",
                "combined",
                "select",
                options=(
                    Option("combined", "One combined PDF"),
                    Option("separate", "Separate PDFs"),
                ),
            ),
            ArgField("--dry-run", "Dry run", "--dry-run", "false", "bool_flag"),
        ),
        confirm_label="Publishes compliance dispatch jobs",
    ),
)
