DROP TABLE IF EXISTS private_institutes_survey_2026;

CREATE TABLE private_institutes_survey_2026 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    institution_name TEXT NOT NULL,
    institute_type TEXT NOT NULL DEFAULT 'School',
    complete_address TEXT NOT NULL,
    location_link_pin TEXT NOT NULL,
    hidden_location_coordinates TEXT,
    tehsil TEXT NOT NULL,
    union_council_name TEXT NOT NULL,
    union_council_number TEXT NOT NULL,
    pp_no TEXT NOT NULL,
    na_no TEXT NOT NULL,
    owner_name TEXT NOT NULL,
    owner_contact_no TEXT NOT NULL,
    principal_name TEXT NOT NULL,
    principal_contact_no TEXT NOT NULL,
    registration_status TEXT NOT NULL,
    registration_license_no TEXT,
    validity_date TEXT,
    building_status TEXT NOT NULL,
    building_ownership TEXT NOT NULL,
    no_of_classrooms INTEGER NOT NULL DEFAULT 0,
    no_of_students INTEGER NOT NULL DEFAULT 0,
    no_of_teachers INTEGER NOT NULL DEFAULT 0,
    classes_offered TEXT NOT NULL,
    quran_teacher_name TEXT NOT NULL,
    quran_teacher_mobile_no TEXT NOT NULL,
    monthly_fee_range TEXT NOT NULL,
    disadvantaged_students_10_percent INTEGER NOT NULL DEFAULT 0,
    separate_washrooms_available TEXT NOT NULL,
    drinking_water_facility TEXT NOT NULL,
    fire_safety_available TEXT NOT NULL,
    cctv_installed TEXT NOT NULL,
    ramp_available TEXT NOT NULL,
    school_council_available TEXT NOT NULL,
    psca_app_installed TEXT NOT NULL,
    punjab_green_school_registration TEXT NOT NULL,
    school_email_address TEXT,
    wing TEXT NOT NULL DEFAULT 'MEE',
    se_submitted_by TEXT NOT NULL DEFAULT 'Not applicable',
    se_aeo_wing TEXT NOT NULL DEFAULT 'Not applicable',
    aeo_name TEXT NOT NULL,
    zonal_head_institute_name TEXT NOT NULL,
    zonal_head_name TEXT NOT NULL,
    zonal_head_contact_no TEXT NOT NULL,
    date_of_visit_report TEXT NOT NULL,
    outside_main_gate_image_url TEXT NOT NULL,
    inside_institute_image_url TEXT NOT NULL,
    submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_private_institutes_survey_submitted_at
ON private_institutes_survey_2026(submitted_at);
