from __future__ import annotations

import re
import unicodedata


HEADING_RE = re.compile(
    r"\b("
    r"complaint\s*(details|remarks|description)|"
    r"applicant\s*details?|"
    r"person\s*(name|address)|"
    r"mobile\s*no|cnic\s*no|"
    r"category|sub\s*category|"
    r"complaint\s*(district|tehsil|no|number|id)"
    r")\b\s*:?",
    re.IGNORECASE,
)

DATE_TIME_RE = re.compile(
    r"\b("
    r"\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|"
    r"\d{4}[-/]\d{1,2}[-/]\d{1,2}|"
    r"\d{1,2}:\d{2}(?::\d{2})?\s*(?:am|pm)?|"
    r"(?:jan|feb|mar|apr|may|jun|jul|aug|sep|sept|oct|nov|dec)[a-z]*\s+\d{1,2},?\s+\d{2,4}"
    r")\b",
    re.IGNORECASE,
)

BOILERPLATE_PHRASES = (
    "this complaint has been lodged through",
    "complaint management system",
    "chief minister complaint cell",
    "prime minister delivery unit",
    "pmdu",
    "crm portal",
    "please look into the matter",
    "necessary action may be taken",
    "forwarded for necessary action",
    "submitted for information",
    "generated by system",
    "computer generated",
)


def normalize_unicode(text: str) -> str:
    value = unicodedata.normalize("NFKC", text or "")
    return value.replace("\u200c", " ").replace("\u200d", " ").replace("\xa0", " ")


def remove_boilerplate(text: str) -> str:
    value = text
    for phrase in BOILERPLATE_PHRASES:
        value = re.sub(re.escape(phrase), " ", value, flags=re.IGNORECASE)
    return value


def clean_remarks(text: str) -> str:
    value = normalize_unicode(text).lower()
    value = HEADING_RE.sub(" ", value)
    value = remove_boilerplate(value)
    value = DATE_TIME_RE.sub(" ", value)
    value = re.sub(r"\b\d{8,}\b", " ", value)
    value = re.sub(r"\b\d{3}-\d{4,}\b", " ", value)
    value = re.sub(r"[_=+*#~`|\\/<>{}\[\]();:\"'“”‘’.,!?-]+", " ", value)
    return re.sub(r"\s+", " ", value).strip()


def clean_identity(text: str) -> str:
    value = normalize_unicode(text).lower()
    value = HEADING_RE.sub(" ", value)
    value = DATE_TIME_RE.sub(" ", value)
    value = re.sub(r"\b\d{5}-?\d{7}-?\d\b", " ", value)
    value = re.sub(r"\b03\d{2}-?\d{7}\b", " ", value)
    value = re.sub(r"[_=+*#~`|\\/<>{}\[\]();:\"'“”‘’.,!?-]+", " ", value)
    return re.sub(r"\s+", " ", value).strip()
